# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

gvc: tailscale
location: aws-us-west-2

image:
  repository: tailscale/tailscale
  tag: latest

nameOverride: tailscale

tailscale:
  name: tailscale

resources:
  cpu: 500m
  memory: 128Mi

locationDNS:
  aws-us-west-2: 172.20.0.10
  aws-us-east-1: 172.20.0.10
  aws-us-east-2: 172.20.0.10
  aws-sa-east-1: 172.20.0.10
  aws-eu-west-2: 172.20.0.10
  aws-eu-central-1: 172.20.0.10
  aws-il-central-1: 172.20.0.10
  gcp-us-west1: 10.67.224.10
  gcp-us-east1: 10.194.112.10
  gcp-us-central1: 10.228.48.10
  gcp-me-west1: 10.110.48.10
  azure-centralus: 10.1.0.10
  azure-eastus2: 10.1.0.10
